platform :ios, '12.0'

target 'UpSpace' do
   use_frameworks!

   # System
   pod 'SwiftLint'

   # Network
   pod 'Alamofire'

   # Utilities
   pod 'SwiftDate'
   pod 'DeviceKit'

   # UI
   pod 'Tabman'
   pod 'SnapKit' 
   pod 'TableKit' 

   # Rx
   pod 'RxSwift'
   pod 'RxAlamofire'
   pod 'RxKeyboard'
   pod 'RxSwiftExt'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
end