name: LeadKit

on:
  push:
    branches: [ feature/test ]
  pull_request:
    branches: [ feature/test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
  
    - name: Run Danger
      env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./setup.sh
        bundle exec danger
