name: LeadKit

on:
  push:
    branches: [ feature/test ]
  pull_request:
    branches: [ feature/test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Bundle Install
      run: bundle install

    - name: Brew Upgrade
      run: |
        brew update-reset
        brew bundle --no-upgrade
  
    - name: Run Danger
      run: bundle exec danger
